from django.urls import path
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    path('', RedirectView.as_view(url='home')),
    path('breakdown/', views.breakdown, name='breakdown'),
    path('overview/', views.overview, name='overview'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('newuser/', views.newuser, name='newuser'),
    path('budget/', views.budget, name='budget'),
    path('newtransactions/', views.newtransactions, name='newtransactions'),
    path('addpendingtransaction/', views.addpendingtransaction, name='addpendingtransaction'),
    path('addhistoricaltime/', views.addhistoricaltime, name='addhistoricaltime'),
    path('deleteperiod/', views.deleteperiod, name='deleteperiod'),
    path('alltransactions/', views.alltransactions, name='alltransactions'),
    path('tasks/', views.tasks, name='tasks'),
    path('goals/', views.goals, name='goals'),
    path('setup/', views.setup, name='setup'),
    path('historicalbalance/', views.historicalbalance, name='historicalbalance'),
    path('color/', views.color, name='color'),
    path('addtransaction/', views.addtransaction, name='addtransaction'),
    path('addtask/', views.addtask, name='addtask'),    
    path('deletetask/', views.deletetask, name='deletetask'),
    path('taskcomplete/', views.taskcomplete, name='taskcomplete'),   
    path('addgoal/', views.addgoal, name='addgoal'),
    path('linkgoaltransaction/', views.linkgoaltransaction, name='linkgoaltransaction'),
    path('addreminder/', views.addreminder, name='addreminder'),
    path('deletereminder/', views.deletereminder, name='deletereminder'),  
    path('addinput/', views.addinput, name='addinput'),
    path('element/', views.element, name='element'),
    path("editsummaryamount", views.editsummaryamount, name="editsummaryamount"),
    path("edit-limits/<int:pk>/", views.edit_categorytype_limits, name="edit_categorytype_limits"),
    path("filtertransactions", views.filtertransactions, name="filtertransactions"),
    path('add-transactions/', views.addtransaction, name='add_transactions'),
    path('duplicateaddtransaction/', views.duplicateaddtransaction, name='duplicateaddtransaction'),
    path("delete-transactions/", views.deletetransactions, name="delete_transactions"),
    path("previousmonthlimit/", views.previousmonthlimit, name="previousmonthlimit"),
    path("updateaccounts/", views.updateaccounts, name="updateaccounts"),
    path("signup/", views.signup, name="signup"),
    path("signin/", views.signin, name="signin"),
    path("home/", views.home, name="home"),
    path("uploadfile/", views.uploadfile, name="uploadfile"),
    path("mapcolumns/", views.mapcolumnsview, name="mapcolumnsview"),
    path("processupload/", views.processupload, name="processupload"),
    path("start-over/", views.start_over, name="start_over"),
    path("getpreview/", views.getpreview, name="getpreview"),
    path("submitupload/", views.submitupload, name="submitupload"),
    path('logoutuser/', views.logoutuser, name='logoutuser'),
]