# Generated by Django 4.2.23 on 2025-09-24 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BudgetApp", "0002_alter_transaction_categorytype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="final_account",
            new_name="destinationaccount",
        ),
        migrations.RenameField(
            model_name="transaction", old_name="account", new_name="sourceaccount",
        ),
    ]
