# Generated by Django 4.2.23 on 2025-10-12 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("BudgetApp", "0003_account_user_accountbalancehistory_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("note", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "sourceaccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BudgetApp.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pendingtransactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
