"""
Django settings for Delta project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
import logging
from dotenv import load_dotenv
from pythonjsonlogger import jsonlogger
from django.db import connections
from django.db.utils import OperationalError
# from logtail.handlers import LogtailHandler

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Get the environment variable, default to 'staging' if not set
ENV = os.environ.get("APP_ENV", "staging")

if ENV != 'production':
    load_dotenv(os.path.join(BASE_DIR, ".env"))

print("ENV", ENV)
# Set the logging level: DEBUG for non-production, WARNING for production
LOGGING_LEVEL = logging.INFO if ENV != "production" else logging.INFO

print("Logging Level: ", LOGGING_LEVEL)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": jsonlogger.JsonFormatter,  # Use jsonlogger for JSON formatting
            "fmt": "%(asctime)s %(name)s %(levelname)s %(message)s %(request_id)s %(user)s",  # Custom format
        },
    },
    "handlers": {
        'logtail': {
            'class': 'logtail.LogtailHandler',
            'source_token': 'REDACTED_LOG_TOKEN',
            'host': 'https://s1671097.eu-nbg-2.betterstackdata.com',
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
            "level": LOGGING_LEVEL,
        },
    },
    "root": {
        "handlers": ["console"],  # Logs will go to both console and file
        "level": LOGGING_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console", "logtail"],
            "level": LOGGING_LEVEL,
            "propagate": True,
        },
    },
}


class Config:
    """
    Centralized configuration management.
    Handles environment variables and validation.
    """
    ENV = os.getenv("APP_ENV", "staging")
    SECRET_KEY = os.getenv("SECRET_KEY")
    DEBUG = os.getenv("DEBUG", "False").lower() == "true"
    DATABASE_URL = os.getenv("DATABASE_URL")
    
    # Supabase Configuration
    SUPABASE_URL = os.getenv("SUPABASE_URL")
    SUPABASE_PUBLIC_KEY = os.getenv("SUPABASE_PUBLIC_KEY")
    SUPABASE_SERVICE_KEY = os.getenv("SUPABASE_SERVICE_KEY")
    SUPABASE_BUCKET = os.getenv("SUPABASE_BUCKET")

    @classmethod
    def validate(cls):
        """Ensures all critical environment variables are set before the app starts."""
        required_vars = [
            "SECRET_KEY",
            "DATABASE_URL",
            "SUPABASE_URL",
            "SUPABASE_PUBLIC_KEY",
            "SUPABASE_SERVICE_KEY",
        ]
        missing = [var for var in required_vars if not getattr(cls, var)]
        if missing:
            raise ValueError(f"Critical Configuration Missing: {', '.join(missing)}")

# Validate configuration
Config.validate()

# Use the centralized configuration for settings
SECRET_KEY = Config.SECRET_KEY
DATABASE_URL = Config.DATABASE_URL
SUPABASE_URL = Config.SUPABASE_URL
SUPABASE_PUBLIC_KEY = Config.SUPABASE_PUBLIC_KEY
SUPABASE_SERVICE_KEY = Config.SUPABASE_SERVICE_KEY
SUPABASE_BUCKET = Config.SUPABASE_BUCKET

# Other
DEBUG = Config.DEBUG


DEFAULT_FILE_STORAGE = "DeltaBApp.supabaseupload.SupabaseStorage"
SUPABASE_USE_SECURE_URLS = True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

ALLOWED_HOSTS = [
    "deltab.onrender.com",
    "deltab-staging.onrender.com",
    "127.0.0.1",
    "localhost",
    "0.0.0.0"
]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://deltab.onrender.com",
]


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,  # adjust this as needed
}


# settings.py

STATIC_URL = '/static/'

# Production
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "DeltaBApp",
]

LOGIN_URL = 'signin'
LOGIN_REDIRECT_URL = 'overview'
AUTH_USER_MODEL = 'DeltaBApp.CustomUser'


MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "middleware.memory_usage.MemoryUsageMiddleware",
    "middleware.performance.PerformanceMiddleware",
    "middleware.logging.RequestLoggingMiddleware",
]

ROOT_URLCONF = "DeltaB.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "DeltaBApp.contextprocessors.typeiconmap",
                "DeltaBApp.contextprocessors.accounticonmap",
            ],
        },
    },
]

WSGI_APPLICATION = "DeltaB.wsgi.application"



DATABASES = {
    "default": dj_database_url.parse(
        Config.DATABASE_URL,
        conn_max_age=300,
        ssl_require=True,
    )
}

try:
    connections['default'].cursor()
except OperationalError as e:
    print("DB ERROR:", e)

if ENV not in ("staging", "production"):
    raise RuntimeError("Invalid Environment")







# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"