# Generated by Django 4.2.23 on 2026-03-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="cached_account_display",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="transaction",
            name="cached_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
