# Generated by Django 4.2.23 on 2025-10-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="accounttype", name="user",),
        migrations.RemoveField(model_name="categorytype", name="user",),
    ]
