# Generated by Django 4.2.23 on 2025-10-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0002_remove_accounttype_user_remove_categorytype_user"),
    ]

    operations = [
        migrations.AlterModelOptions(name="account", options={"ordering": ["order"]},),
        migrations.AddField(
            model_name="account",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
