# Generated by Django 4.2.23 on 2025-10-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0003_alter_account_options_account_order"),
    ]

    operations = [
        migrations.AlterModelOptions(name="account", options={},),
        migrations.AlterModelOptions(
            name="accounttype", options={"ordering": ["order"]},
        ),
        migrations.RemoveField(model_name="account", name="order",),
        migrations.AddField(
            model_name="accounttype",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
