# Generated by Django 4.2.23 on 2026-03-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0003_alter_transaction_cached_account_display_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="cached_account_display",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="cached_amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
