# Generated by Django 4.2.23 on 2025-10-27 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0004_alter_account_options_alter_accounttype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="accounttype", options={},),
        migrations.RemoveField(model_name="accounttype", name="order",),
    ]
