# Generated by Django 4.2.23 on 2025-10-27 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0005_alter_accounttype_options_remove_accounttype_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("complete", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("complete", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DeltaBApp.category",
                    ),
                ),
                (
                    "categorytype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DeltaBApp.categorytype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("startdate", models.DateField()),
                ("enddate", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DeltaBApp.category",
                    ),
                ),
                (
                    "categorytype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DeltaBApp.categorytype",
                    ),
                ),
            ],
        ),
    ]
