# Generated by Django 4.2.23 on 2025-11-03 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0008_monthlysummary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal", old_name="startdate", new_name="date",
        ),
        migrations.RemoveField(model_name="goal", name="category",),
        migrations.RemoveField(model_name="goal", name="categorytype",),
        migrations.RemoveField(model_name="goal", name="enddate",),
        migrations.AddField(
            model_name="goal",
            name="transactions",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactiongoals",
                to="DeltaBApp.transaction",
            ),
            preserve_default=False,
        ),
    ]
