# Generated by Django 4.2.23 on 2025-11-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0009_rename_startdate_goal_date_remove_goal_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="transactions",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactiongoals",
                to="DeltaBApp.transaction",
            ),
        ),
    ]
