# Generated by Django 4.2.23 on 2025-11-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0010_alter_goal_transactions"),
    ]

    operations = [
        migrations.RemoveField(model_name="goal", name="transactions",),
        migrations.AddField(
            model_name="goal",
            name="transactions",
            field=models.ManyToManyField(
                blank=True, related_name="goals", to="DeltaBApp.transaction"
            ),
        ),
    ]
