# Generated by Django 4.2.23 on 2025-11-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0011_remove_goal_transactions_goal_transactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=255),
        ),
    ]
