# Generated by Django 4.2.23 on 2025-11-23 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0013_institution_remove_pendingtransaction_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institutions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
