# Generated by Django 4.2.23 on 2025-11-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0014_institution_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="institution", name="type",),
    ]
