# Generated by Django 4.2.23 on 2025-11-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0015_remove_institution_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="polarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("positive", "Positive outflow"),
                    ("negative", "Negative outflow"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
