# Generated by Django 4.2.23 on 2025-11-30 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0016_account_polarity"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="polarity",),
    ]
