# Generated by Django 4.2.23 on 2025-11-30 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0017_remove_account_polarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 30, 21, 58, 59, 256862, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
