# Generated by Django 4.2.23 on 2025-12-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0020_remove_account_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("America/New_York", "America/New_York"),
                    ("America/Chicago", "America/Chicago"),
                    ("America/Denver", "America/Denver"),
                    ("America/Los_Angeles", "America/Los_Angeles"),
                    ("Europe/London", "Europe/London"),
                    ("Europe/Paris", "Europe/Paris"),
                    ("Asia/Tokyo", "Asia/Tokyo"),
                    ("Asia/Kolkata", "Asia/Kolkata"),
                    ("Australia/Sydney", "Australia/Sydney"),
                ],
                default="America/Chicago",
                max_length=50,
            ),
        ),
    ]
