# Generated by Django 4.2.23 on 2025-12-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0022_alter_customuser_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="base_key",
            field=models.CharField(db_index=True, default="new", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="import_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="manual_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
