# Generated by Django 4.2.23 on 2025-12-01 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0023_transaction_base_key_transaction_import_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="transaction", name="is_manual",),
    ]
