# Generated by Django 4.2.23 on 2025-12-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0024_remove_transaction_is_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="statementupload",
            name="filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="statementupload",
            name="supabase_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
