# Generated by Django 4.2.23 on 2025-12-02 00:27

import DeltaBApp.supabaseupload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0025_statementupload_filename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementupload",
            name="file",
            field=models.FileField(
                storage=DeltaBApp.supabaseupload.SupabaseStorage,
                upload_to="statements/",
            ),
        ),
    ]
