# Generated by Django 4.2.23 on 2025-12-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0026_alter_statementupload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingtransaction",
            name="base_key",
            field=models.CharField(db_index=True, default="new", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pendingtransaction",
            name="import_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
        migrations.AddField(
            model_name="pendingtransaction",
            name="manual_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
