# Generated by Django 4.2.23 on 2025-12-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0027_pendingtransaction_base_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
