# Generated by Django 4.2.23 on 2025-12-06 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0028_alter_institution_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="DeltaBApp.categorytype",
            ),
            preserve_default=False,
        ),
    ]
