# Generated by Django 4.2.23 on 2025-12-13 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0030_entry_paired_entry_entry_reconciled"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="DeltaBApp.account",
            ),
        ),
    ]
