# Generated by Django 4.2.23 on 2025-12-13 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0031_category_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_categories",
                to="DeltaBApp.account",
            ),
        ),
    ]
