# Generated by Django 4.2.23 on 2025-12-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0032_alter_category_account"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="account",),
    ]
