# Generated by Django 4.2.23 on 2025-12-18 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0034_entry_destination_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingentry",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pendingentries",
                to="DeltaBApp.account",
            ),
        ),
    ]
