# Generated by Django 4.2.23 on 2025-12-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0035_alter_pendingentry_account"),
    ]

    operations = [
        migrations.RemoveField(model_name="entry", name="destination_account",),
        migrations.RemoveField(model_name="entry", name="paired_entry",),
        migrations.RemoveField(model_name="entry", name="reconciled",),
        migrations.AddField(
            model_name="transaction",
            name="transfer_id",
            field=models.UUIDField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
