# Generated by Django 4.2.23 on 2025-12-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0036_remove_entry_destination_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="destination_account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="DeltaBApp.account",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="paired",
            field=models.BooleanField(default=True),
        ),
    ]
