# Generated by Django 4.2.23 on 2025-12-23 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0037_entry_destination_account_transaction_paired"),
    ]

    operations = [
        migrations.RemoveField(model_name="entry", name="destination_account",),
    ]
