# Generated by Django 4.2.23 on 2025-12-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0038_remove_entry_destination_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="destination_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="DeltaBApp.account",
            ),
        ),
    ]
