# Generated by Django 4.2.23 on 2026-01-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0039_entry_destination_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction", old_name="note", new_name="user_note",
        ),
        migrations.RemoveField(model_name="transaction", name="paired",),
        migrations.RemoveField(model_name="transaction", name="transfer_id",),
        migrations.AddField(
            model_name="entry",
            name="bank_note",
            field=models.CharField(default="default need edit", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entry", name="paired", field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="DeltaBApp.institution",
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="DeltaBApp.transaction",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category", unique_together={("user", "type", "name")},
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.CheckConstraint(
                check=models.Q(("limit__gte", 0)), name="limit_greater_than_equal_zero"
            ),
        ),
    ]
