# Generated by Django 4.2.23 on 2026-01-24 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("DeltaBApp", "0040_rename_note_transaction_user_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="DeltaBApp.transaction",
            ),
        ),
    ]
